Update patch set 8
Patch Set 8:

> csit-vpp-device-master-ubuntu1804-1n-skx/2944/ : FAILURE

I am out of ideas, it is hard to tell which value is causing problems:
https://logs.fd.io/production/vex-yul-rot-jenkins-1/csit-vpp-device-master-ubuntu1804-1n-skx/2944/archives/log.html.gz#s1-s1-s1-s4-s5-t1-k2-k9-k19

error: cannot convert argument to integer 	
16:48:38.116 	DEBUG 	Traceback (most recent call last):
  File "/w/workspace/csit-vpp-device-master-ubuntu1804-1n-skx/resources/libraries/python/Policer.py", line 181, in policer_set_configuration
    reply = papi_exec.add(cmd, **args_in).get_reply(err_msg)
  File "/w/workspace/csit-vpp-device-master-ubuntu1804-1n-skx/resources/libraries/python/PapiExecutor.py", line 393, in get_reply
    replies = self.get_replies(err_msg=err_msg)
  File "/w/workspace/csit-vpp-device-master-ubuntu1804-1n-skx/resources/libraries/python/PapiExecutor.py", line 377, in get_replies
    return self._execute(err_msg=err_msg)
  File "/w/workspace/csit-vpp-device-master-ubuntu1804-1n-skx/resources/libraries/python/PapiExecutor.py", line 503, in _execute
    reply = papi_fn(**command["api_args"])
  File "/tmp/tmpjXxukL/usr/lib/python2.7/dist-packages/vpp_papi/vpp_papi.py", line 90, in __call__
  File "/tmp/tmpjXxukL/usr/lib/python2.7/dist-packages/vpp_papi/vpp_papi.py", line 411, in f
  File "/tmp/tmpjXxukL/usr/lib/python2.7/dist-packages/vpp_papi/vpp_papi.py", line 624, in _call_vpp
  File "/tmp/tmpjXxukL/usr/lib/python2.7/dist-packages/vpp_papi/vpp_serializer.py", line 528, in pack
  File "/tmp/tmpjXxukL/usr/lib/python2.7/dist-packages/vpp_papi/vpp_serializer.py", line 101, in pack


I this cases I usually resort to generous usage of logger.debug().
Output the repr of args_in and hopefully we will see which value is wrong.

Patch-set: 8
Label: Code-Review=0