fix(bisect): Adjust bash script for Ubuntu 24.04
Newer git versions gives:
  error: cannot delete branch 'earliest' used by worktree
if branches involved in bisect are to be deleted before bisect ends.

+ Remove comment about reliably deleting branches after failure,
  as having them may be useful for debugging (and does not matter in CI).
+ Move branch cleanup to the start, and allow it to fail in CI.

Change-Id: Iebee5be5e10ae2f4de8218f70952c66b16b2a030
Signed-off-by: Vratko Polak <vrpolak@cisco.com>
(cherry picked from commit 14e4f9447ca85613ec6cdfa553464b02a3d62fab)