Update patch set 9
Patch Set 9:

(2 comments)

> csit-verify-tox-master/3839/ : FAILURE

> test type is not matching suite naming rule!
> packet encapsulation on L2 layer is not matching testcase naming rule!
> ERROR:   tc_naming: commands failed

Oh, I forgot about that checker.
It [1] needs to be educated about new test types as well.

[1] https://github.com/FDio/csit/blob/master/resources/libraries/bash/entry/check/tc_naming.sh

Patch-set: 9
Label: Code-Review=0