Update patch set 7
Patch Set 7:

One more recap. Now I think there is only one relevent issue, time unit (time precision is not an issue for now).

openmetrics_official:

> Timestamps MUST be Unix Epoch in seconds.

openmetrics_32030:

> proper epoch in milisecond

Ok, now conversion methods.

> Epoch to milisecond https://pythonguides.com/python-epoch-to-datetime/

"Python epoch to DateTime"

  datetime.datetime.fromtimestamp(epochtime)

"Python epoch to DateTime milliseconds"

  datetime.datetime.fromtimestamp(millseconds)

You can see it is the same call, so the "milliseconds" here is referring to precision, NOT units (which are still seconds).

"Python epoch DateTime to milliseconds"

  milliseconds = date_obj.timestamp() * 1000

Here multiplication by 1000 means we are really converting units from seconds to milliseconds.

Example values and their conversions.

Example value from OpenMetrics:

> 1604676851.123456789

Converting from seconds:

  print(datetime.datetime.fromtimestamp(1604676851.123456789))
  2020-11-06 16:34:11.123457

Converting as if from milliseconds:

  print(datetime.datetime.fromtimestamp(1604676851.123456789 * 1000))
  ValueError: year 52820 is out of range

Example value from a random verify run:

  vpp_version_version_info{version=\"v21.10-rc0~73-g5de9772c1~b1347\"} 1.0 1872425853

Converting as if from seconds:

  print(datetime.datetime.fromtimestamp(1872425853))
  2029-05-02 16:17:33

Converting from milliseconds:

  print(datetime.datetime.fromtimestamp(1872425853 / 1000))
  1970-01-22 17:07:05.853000

Neither is valid. https://docs.python.org/3/library/time.html say about monotonic():

> The reference point of the returned value is undefined,
> so that only the difference between the results of two calls is valid.

So you are right, I screwed up. Let me fix that.

Patch-set: 7