Update patch set 126
Patch Set 126:

Failure caused by occasional issue with t-rex astf profile load [0]:
trex.common.trex_exceptions.TRexError: Could not load profile, error: Invalid state: Delete profile, should be one of following: Idle,Loaded profile

Will be discussed with t-rex dev team.

[0] https://logs.fd.io/production/vex-yul-rot-jenkins-1/csit-vpp-perf-verify-master-2n-skx/1717/archives/log.html.gz#s1-s1-s1-s1-s10-t1-k2-k13-k1-k6-k1-k1

Patch-set: 126
Reviewer: Gerrit User 207 <207@6d2eb258-4fe2-443e-8a38-ca81da23d4c2>