Add defaultbranch to .gitreview
Without having different values in different branches,
"git review" has trouble contributing to non-master branches.

Here is a console output of what happens without this:

vrpolak@ds:~$ git clone ssh://vrpolak@gerrit.fd.io:29418/csit.git
Cloning into 'csit'...
remote: Counting objects: 2135, done
remote: Finding sources: 100% (20/20)
remote: Total 21750 (delta 0), reused 21734 (delta 0)
Receiving objects: 100% (21750/21750), 11.43 MiB | 1.05 MiB/s, done.
Resolving deltas: 100% (11295/11295), done.
vrpolak@ds:~$ cd csit
vrpolak@ds:~/csit$ git checkout rls1804
Branch rls1804 set up to track remote branch rls1804 from origin.
Switched to a new branch 'rls1804'
vrpolak@ds:~/csit$ git review -s
Creating a git remote called "gerrit" that maps to:
    ssh://vrpolak@gerrit.fd.io:29418/csit.git
vrpolak@ds:~/csit$ touch DELETE_ME.txt
vrpolak@ds:~/csit$ git add DELETE_ME.txt
vrpolak@ds:~/csit$ git commit -sm'DO_NOT_MERGE: git review test'
[rls1804 0ba9aa3e] DO_NOT_MERGE: git review test
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 DELETE_ME.txt
vrpolak@ds:~/csit$ git review -y
Errors running git rebase -p -i remotes/gerrit/master
error: could not apply 39ce5d87... Set correct paths to vpp stable/1804 and use vpp stable/1804 builds

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
Could not pick 39ce5d87070867c5a906e2a2ed8a683f975289f4
It is likely that your change has a merge conflict. You may resolve it in the working tree now as described above and then run 'git review' again, or if you do not want to resolve it yet (note that the change can not merge until the conflict is resolved) you may run 'git rebase --abort' then 'git review -R' to upload the change without rebasing.
vrpolak@ds:~/csit$

And here is console output of what happens with this Change:

vrpolak@ds:~$ git clone ssh://vrpolak@gerrit.fd.io:29418/csit.git
Cloning into 'csit'...
remote: Counting objects: 1805, done
remote: Finding sources: 100% (6/6)
remote: Total 21736 (delta 0), reused 21732 (delta 0)
Receiving objects: 100% (21736/21736), 11.41 MiB | 871.00 KiB/s, done.
Resolving deltas: 100% (11295/11295), done.
vrpolak@ds:~$ cd csit
vrpolak@ds:~/csit$ git checkout rls1804
Branch rls1804 set up to track remote branch rls1804 from origin.
Switched to a new branch 'rls1804'
vrpolak@ds:~/csit$ git review -s
Creating a git remote called "gerrit" that maps to:
    ssh://vrpolak@gerrit.fd.io:29418/csit.git
vrpolak@ds:~/csit$ git fetch https://gerrit.fd.io/r/csit refs/changes/91/12491/3 && git cherry-pick FETCH_HEAD
remote: Counting objects: 1808, done
remote: Finding sources: 100% (3/3)
remote: Total 3 (delta 1), reused 3 (delta 1)
Unpacking objects: 100% (3/3), done.
From https://gerrit.fd.io/r/csit
 * branch              refs/changes/91/12491/3 -> FETCH_HEAD
[rls1804 09a05f6a] Add defaultbranch to .gitreview
 Date: Wed May 9 12:04:04 2018 +0200
 1 file changed, 1 insertion(+), 1 deletion(-)
vrpolak@ds:~/csit$ touch DELETE_ME.txt
vrpolak@ds:~/csit$ git add DELETE_ME.txt
vrpolak@ds:~/csit$ git commit -sm'DO_NOT_MERGE: git review test'
[rls1804 595f4afa] DO_NOT_MERGE: git review test
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 DELETE_ME.txt
vrpolak@ds:~/csit$ git review -y
remote: Processing changes: new: 1, updated: 1, refs: 2, done
remote: (W) No changes between prior commit 9146b22 and new commit 09a05f6
remote:
remote: New Changes:
remote:   https://gerrit.fd.io/r/12699 DO_NOT_MERGE: git review test
remote:
remote:
remote: Updated Changes:
remote:   https://gerrit.fd.io/r/12491 Add defaultbranch to .gitreview
remote:
To ssh://gerrit.fd.io:29418/csit.git
 * [new branch]        HEAD -> refs/publish/rls1804
vrpolak@ds:~/csit$

Change-Id: I4a6797a8646c26bdae49eb4fcc9dbd463b97ab7b
Signed-off-by: Vratko Polak <vrpolak@cisco.com>