Update patch set 1
Patch Set 1:

(2 comments)

> This job fails, unrelated to this changeset

Not all failures visible in console lead to -1. We tolerate some of them (mainly because they are hard to fix), but still include them in case somebody wants to start fixing them.:

___________________________________ summary ____________________________________
  tc_naming: commands succeeded
  tc_coverage: commands succeeded
ERROR:   copyright_year: commands failed
  gpl_license: commands succeeded
  new_line_length: commands succeeded
  line_length: commands succeeded
  autogen: commands succeeded
  pylint: commands succeeded
  doc_verify: commands succeeded

Patch-set: 1
Reviewer: Gerrit User 1263 <1263@6d2eb258-4fe2-443e-8a38-ca81da23d4c2>