feat(pip): set jinja2==3.0.3
- jinja2>=3.1.0 causes ImportError: cannot import name 'environmentfilter'
  from 'jinja2'

Change-Id: If293d932775474a1eacc019210fb58ee7601c99f
Signed-off-by: Tibor Frank <tifrank@cisco.com>
(cherry picked from commit dbad114b252b969523d81372c9065d16b78be676)