remove dpdk_nic_bind.py dependency
dpdk_nic_bind.py from <trex>/scripts/ is out of date, often bumped into
errors when using it to bind nic port, e.g.

/usr/bin/python3 dpdk_nic_bind.py --bind=vfio-pci 0000:ca:00.0
/opt/trex-core-3.00/scripts/dpdk_nic_bind.py:40: DeprecationWarning:
The distutils package is deprecated and slated for removal in Python 3.12.
Use setuptools or check PEP 632 for potential alternatives
  from distutils.util import strtobool
Error: bind failed for 0000:ca:00.0 - Cannot bind to driver vfio-pci

so remove dpdk_nic_bind.py dependency in csit.

Signed-off-by: Yulong Pei <yulong.pei@intel.com>
Change-Id: I5a3f641cd77d339aa7a213f410ce2efe7c322b8a
Signed-off-by: Yulong Pei <yulong.pei@intel.com>