Update patch set 16
Patch Set 16: Code-Review-1

> TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

I need to fix something.

Patch-set: 16
Label: Code-Review=-1